#-------------------------------
# General Site Settings

title: Kunal Saluja
baseurl: "/ksaluja15.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Kunal Saluja
author-avatar: 12.JPG


#-------------------------------
# Contact links
twitter: https://twitter.com/ksaluja15/ # Add your Facebook handle
linkedin: https://www.linkedin.com/in/ksaluja/
github: https://github.com/ksaluja15/

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: kunalsaluja # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
